### ISSUE TITLE
Extraneous newline with multi-value arrays

### ISSUE THREAD

**Issue by nabijaczleweli** [alexcrichton/toml-rs#110]
Given:
```rust
#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct User {
    pub name: String,
    pub surname: String,
}

#[derive(Debug, Clone, Hash, PartialEq, Eq, RustcEncodable, RustcDecodable)]
struct Users {
    pub user: Vec<User>,
}

encode_str(&Users {
    user: vec![
        User {
            name: "John".to_string(),
            surname: "Doe".to_string(),
        },
        User {
            name: "Jane".to_string(),
            surname: "Dough".to_string(),
        },
    ],
))
```

One'd expect the result to be
```toml
[[user]]
name = "John"
surname = "Doe"

[[user]]
name = "Jane"
surname = "Dough"
```

But the output actually is
```toml
# Empty line
[[user]]
name = "John"
surname = "Doe"

[[user]]
name = "Jane"
surname = "Dough"
```

Which is rather ugly
