### ISSUE TITLE
Getting error on (seemingly) valid toml

### ISSUE THREAD

**Issue by matthiasbeyer** [alexcrichton/toml-rs#191]
Hi,

I get an error when `toml::de::from_str()`ing the following toml, which seems to be valid with [this online tool](http://toml-online-parser.ovonick.com/):

```toml
# This is a example configuration file for the imag suite.
# It is written in TOML

#
# Configuration options for the user interface
#
[ui]

#
# Configuration options for the commandline user interface
#
[ui.cli]

# History file path for readline. Will be created by imag if it does not exist.
readline_history_file = "/tmp/readline.history"

# Number of lines to safe in the history file
readline_history_size = 100

# Ignore duplicated lines
readline_history_ignore_dups = true

# Tell if lines which begin with a space character are saved or not in the
# history list.
readline_history_ignore_space = true

# The prompt string to use
readline_prompt = ">> "

[store]

# Set to false if you do not want imag to create the directory where the store
# lives implicitely
implicit-create = false

```

I'm reading the file with

```
let content = {
    let mut s = String::new();
    let f = File::open(path);
    if f.is_err() {
        return None
    }
    let mut f = f.unwrap();
    f.read_to_string(&mut s).ok();
    s
};

    match ::toml::de::from_str(&content[..]) {
        Ok(res) => res,
        Err(e) => {
            write!(stderr(), "Config file parser error:").ok();
            let _ = e
                .line_col()
                .map(|(line, col)| write!(stderr(), "Line: {}, Col: {}", line, col).ok());
            write!(stderr(), ":").ok();
            trace_error(&e);
            debug!("{:?}", e);
            None
        }
```

So it is basically just reading the file and passing it to the `from_str` fn. The error is:

```
Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: map, expected option", key: [] } }
```

I'm at my wits end ... I cannot see the error.
