### ISSUE TITLE
Duplicate table not detected.

### ISSUE THREAD

**Issue by ehuss** [alexcrichton/toml-rs#279]
The following TOML is accepted, but it should be rejected due to the duplicate table.

```toml
[dependencies.openssl-sys]
version = "0.5.2"

[dependencies]
libc = "0.1"

[dependencies]
bitflags = "0.1.1"
```

Discovered in these 3 `Cargo.toml` manifests on crates.io:
- https://crates.io/crates/pnetlink/0.0.1
- https://crates.io/crates/pnetlink/0.0.2
- https://crates.io/crates/openssl/0.5.2

I don't think I understand the `cur_parent` dance in `MapVisitor` well enough to fix this.
