### ISSUE TITLE
Large TOML document performance

### ISSUE THREAD

**Issue by yuvadm** [alexcrichton/toml-rs#342]
I'm attempting to read a large-ish TOML document like so:

```rust
println!("Reading toml size {}", s.len());
let t = toml::from_str(s).unwrap();
```

where the `str` size is around 4MB (this is an auto-generated TOML, obviously). The file is essentially a lot of very small tables in the following format:

```toml
[table-id-1]
name = "Foo"
url = "http://example.com"
tags = ["tag-name"]
```

The loading time is unreasonable, spinning the CPU up to 100% and taking way too long, over a minute before I kill the process.

Am I wrong to expect this library to be able to handle files that big?
