### ISSUE TITLE
incorrect duplicate key error

### ISSUE THREAD

**Issue by samuelcolvin** [alexcrichton/toml-rs#367]
The following TOML is [included in the main toml docs as valid](https://github.com/toml-lang/toml#table)

```toml
[fruit]
apple.color = "red"
apple.taste.sweet = true

[fruit.apple.texture]  # you can add sub-tables
smooth = true
```

But gives the error

    duplicate key: `apple` for key `fruit` at line 5 column 1

When parsed with toml-rs.
