### ISSUE TITLE
Cannot borrow multi-line strings?

### ISSUE THREAD

**Issue by alexschrod** [alexcrichton/toml-rs#397]
I encountered something I find to be somewhat perplexing. I have this relatively simple type that I want to deserialize from TOML into; it looks like this:
```rust
#[derive(Deserialize, Debug)]
pub struct Template<'t> {
    #[serde(borrow)]
    pub variables: Option<HashMap<&'t str, &'t str>>,
}
```
It works... until there's a newline in the string. In other words, this deserializes just fine:
```toml
[variables]
foo = "bar"
```
as does this:
```toml
[variables]
foo = """bar"""
```
but this fails with an error:
```toml
[variables]
foo = """bar
baz"""
```
The error given is:
```
invalid type: string "bar\nbaz", expected a borrowed string for key `variables.foo` at line 2 column 7'
```
What is it about a newline character that suddenly makes this balk? Newline characters can be borrowed too! 😅
