### ISSUE TITLE
example to preserve ordering of dict?

### ISSUE THREAD

**Issue by mimoo** [alexcrichton/toml-rs#437]
Hey!

I'm trying to parse a dictionary in a .toml file and the result doesn't seem to preserve the ordering.
I read here: https://docs.rs/toml/0.5.8/toml/map/index.html that I should enable the preserve_order but it doesn't seem to do anything. Is there an example somewhere?

**Comment by ehuss** [comment]
When having an issue, it is usually helpful to show what you've tried and what results you get.  There isn't anything special about what needs to be done different to handle the preserved order, the keys just come out of the map in a different order.  For example:


```rust
fn main() {
    let s = "
[foo]
z = 2
a = 1

[bar]
y = 4
x = 3
";
    let v: toml::Value = toml::from_str(s).unwrap();
    for val in v.as_table().unwrap().iter() {
        println!("{:?}", val);
    }
}
```

Without preserved order looks like:

```
("bar", Table({"x": Integer(3), "y": Integer(4)}))
("foo", Table({"a": Integer(1), "z": Integer(2)}))
```

With preserved order looks like:

```
("foo", Table({"z": Integer(2), "a": Integer(1)}))
("bar", Table({"y": Integer(4), "x": Integer(3)}))
```

The dependency declaration should look something like:

```toml
[dependencies]
toml = { version = "0.5.8", features = ["preserve_order"] }
```

**Comment by mimoo** [comment]
Thanks for the pointer! This still doesn't seem to work. I'm using the following struct:

```rust
pub struct Specification {
    /// information about a specification
    pub metadata: Metadata,
    /// vec of files
    pub sections: BTreeMap<String, Vec<String>>,
}
```

and parse it via:

```rust
    let mut file = File::open(spec_file).unwrap();
    let mut content = String::new();
    file.read_to_string(&mut content)
        .unwrap_or_else(|e| panic!("{}", e));
    toml::from_str(&content).unwrap_or_else(|e| panic!("{}", e))
```

my toml file:

```toml
[sections]
overview = ["overview.md"]
indexes = ["../../dlog/kimchi/src/index.rs"]
prover = ["../../dlog/kimchi/src/prover.rs"]
verifier = ["../../dlog/kimchi/src/verifier.rs"]
```

ends up being parsed as:

```
    sections: {
        "indexes": [
            "../../dlog/kimchi/src/index.rs",
        ],
        "overview": [
            "overview.md",
        ],
        "prover": [
            "../../dlog/kimchi/src/prover.rs",
        ],
        "verifier": [
            "../../dlog/kimchi/src/verifier.rs",
        ],
```
