### ISSUE TITLE
Recommended ways to deserialize arbitrary tables?

### ISSUE THREAD

**Issue by xpe** [alexcrichton/toml-rs#440]
What are some recommended ways to deserialize a TOML file with arbitrary tables? In other words, the table names are unknown in advance. For example:

```toml
[Michael Palin]
born = 1943-05-05

[Graham Chapman]

[Terry Gilliam]
born = 1940-11-22
born_in = "Minnesota"

[Eric Idle]
born = 1943-03-29

[John Cleese]
born = 1939-10-27
noteworthy = "The Bemaraha woolly lemur (Avahi cleesei), also known as Cleese's woolly lemur, is native to western Madagascar. The scientist who discovered the species named it after Cleese, mainly because of Cleese's fondness for lemurs and his efforts at protecting and preserving them."

[Terry Jones]
noteworthy = "Jones was a well-respected medieval historian, having written several books and presented television documentaries about the period"
died = 2020-01-21
born = 1942-02-01
```
