### ISSUE TITLE
Question: how do you generate an array-of-tables

### ISSUE THREAD

**Issue by timabell** [alexcrichton/toml-rs#465]
Thanks for the project.

I've spent hours trying to figure out how to get toml-rs to generate a toml file that has an [array of tables](https://toml.io/en/v1.0.0#array-of-tables) in it like the example in the test suite [/test-suite/tests/valid/table-array-many.toml](https://github.com/alexcrichton/toml-rs/blob/master/test-suite/tests/valid/table-array-many.toml)

```toml
[[people]]
first_name = "Bruce"
last_name = "Springsteen"

[[people]]
first_name = "Eric"
last_name = "Clapton"

[[people]]
first_name = "Bob"
last_name = "Seger"
```

Does anyone know what rust code I would have to write to make it product something like that?

Thanks
